version: '3.8'

services:
  api:
    build: .
    container_name: neckarmedia-api
    env_file: .env
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      # Mount database and data files
      - ./neckarmedia.db:/app/neckarmedia.db
      - ./latest_info.json:/app/latest_info.json
      - ./blog_posts.json:/app/blog_posts.json
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

networks:
  app-network:
    driver: bridge


