name: Deploy to VPS

# Run this workflow on pushes to the "main" branch (modify as needed).
on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out your repo code
      - name: Check out code
        uses: actions/checkout@v3

      # Step 3: Build a Docker image (example) - or skip if you build on the VPS
      - name: Build Docker image
        run: docker build -t myragdemo:latest .

      # Step 4: Push the Docker image to your Docker registry (optional)
      #         If you want the VPS to pull it from Docker Hub or GHCR
      #
      # - name: Log in to Docker
      #   run: |
      #     echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
      #
      # - name: Tag & push image
      #   run: |
      #     docker tag myragdemo:latest ${{ secrets.DOCKERHUB_USERNAME }}/myragdemo:latest
      #     docker push ${{ secrets.DOCKERHUB_USERNAME }}/myragdemo:latest

      # Step 5: SSH into VPS and run deployment commands
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.VPS_HOST }}       
          username: ${{ secrets.VPS_USER }}     
          key: ${{ secrets.VPS_SSH_KEY }}       
          # If you used a key passphrase, you'd also include: passphrase: ${{ secrets.VPS_KEY_PASSPHRASE }}
          script: |
            cd /home/rag-bot/myragapp
            # For example, if you're storing a docker-compose.yml in that directory:
            docker-compose down
            docker-compose up -d --build

            # Alternatively, if you rely on pulling from a registry:
            # docker pull ${{ secrets.DOCKERHUB_USERNAME }}/myragdemo:latest
            # docker-compose down
            # docker-compose up -d
